services:
  segmentation:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: segmentation
    volumes:
      - .:/alsuser
    ports:
      - "8000:8000"
    command: jupyter lab --ip=0.0.0.0 --port=8000 --no-browser --allow-root --NotebookApp.token=''
    restart: unless-stopped
